language: python

python:
 - "3.6"

install:
 - pip install codecov
 - pip install coverage

script:
 - python -m unittest discover -v ./ # command to run unit test
 - coverage run test.py # command to run code coverage

after_success:
 - codecov --token=fa55efdf-8726-432a-9382-a8952bf6184c # upload coverage report to codecov.io
deploy:
 provider: s3
 access_key_id: $AWS_AccessKey_Id
 secret_access_key: $AWS_SecretKey
 bucket: yahye
 local-dir: s3_play/html_files
 region: us-east-1
 skip_cleanup: true
